language: objective-c
osx_image: xcode8

env:
  - ACTION=clean && test  PLATFORM=Mac     DESTINATION='platform=OS X'
  - ACTION=clean && test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
  - ACTION=clean && build PLATFORM=watchOS DESTINATION='platform=watchOS Simulator,name=Apple Watch - 38mm'
  - ACTION=clean && test  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'

script:
  - set -o pipefail && xcodebuild -scheme DBNetworkStack -destination "$DESTINATION" $ACTION | xcpretty