matrix:
  allow_failures:
    - os: linux
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: generic
      before_install:
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - cd ..
        - export SWIFT_VERSION=swift-4.0.2-RELEASE
        - wget https://swift.org/builds/swift-4.0.2-release/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz
        - tar xzf $SWIFT_VERSION-ubuntu14.04.tar.gz
        - export PATH="${PWD}/${SWIFT_VERSION}-ubuntu14.04/usr/bin:${PATH}"
        - cd DBNetworkStack
      script:
        - swift test --verbose
    - os: osx
      osx_image: xcode9.1
      language: objective-c
      env: "macOS"
      script:
        - set -o pipefail && xcodebuild -scheme DBNetworkStack -destination "platform=tvOS Simulator,name=OS X" test | xcpretty
        - set -o pipefail && xcodebuild -scheme DBNetworkStack -destination "platform=tvOS Simulator,name=Apple TV" test | xcpretty
        - set -o pipefail && xcodebuild -scheme DBNetworkStack -destination "platform=watchOS Simulator,name=Apple Watch - 38mm" build | xcpretty
        - set -o pipefail && xcodebuild -scheme DBNetworkStack -destination "platform=iOS Simulator,name=iPhone SE" test | xcpretty
        - swift test & pod spec lint --allow-warnings & carthage build --no-skip-current
      after_success:
        - bash <(curl -s https://codecov.io/bash)